package dev.teogor.traverse.demo.feature

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.FilledTonalButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import dev.teogor.traverse.demo.TraverseScreens
import dev.teogor.traverse.demo.ui.ShowcaseScaffold

// ── AnnotationsShowcaseScreen ─────────────────────────────────────────────────

private data class SectionEntry(val heading: String, val body: String, val code: String? = null)

private val OVERVIEW_SECTIONS = listOf(
    SectionEntry(
        heading = "1. @TraverseScreen",
        body = "Marks a Destination subclass as a full-screen entry. The KSP processor reads this annotation to generate registration helpers.",
        code = """
@TraverseScreen
@ScreenMeta(name = "Home", group = "main")
@Serializable data object Home : Destination
        """.trimIndent(),
    ),
    SectionEntry(
        heading = "2. @DeepLink (repeatable)",
        body = "Attach one or more URI patterns. KSP generates a {Class}Route object with the list and a built-in URI builder.",
        code = """
@TraverseScreen
@DeepLink("https://example.com/user/{userId}")
@DeepLink("app://profile/{userId}")
@Serializable
data class Profile(val userId: String) : Destination
// KSP generates:
// ProfileRoute.deepLinks
// ProfileRoute.buildDeepLink(userId)
        """.trimIndent(),
    ),
    SectionEntry(
        heading = "3. @Transition",
        body = "Declare a per-screen transition preset. KSP writes the transitionSpec= argument into traverseAutoGraph().",
        code = """
@TraverseScreen
@Transition(TransitionPreset.SLIDE_AND_FADE, durationMillis = 350)
@Serializable
data object Settings : Destination
        """.trimIndent(),
    ),
    SectionEntry(
        heading = "4. @ScreenMeta",
        body = "Human-readable metadata (name, description, group). Used for analytics, debug overlays, and ScreenRegistry queries.",
        code = """
@ScreenMeta(
    name = "Feature Detail",
    description = "Shows typed args from a deep link.",
    group = "demo",
)
        """.trimIndent(),
    ),
    SectionEntry(
        heading = "5. traverseAutoGraph() — KSP output",
        body = "Instead of listing every screen<T> { } manually, call the generated function for the entire module.",
        code = """
TraverseHost(startDestination = Home) {
    traverseAutoGraph(
        homeContent = { HomeScreen() },
        profileContent = { dest -> ProfileScreen(dest.userId) },
        settingsContent = { SettingsScreen() },
    )
}
        """.trimIndent(),
    ),
    SectionEntry(
        heading = "6. Type-safe navigate extensions",
        body = "KSP generates navigateTo{Class}(params) for every parameterised destination, replacing manual navigate(Profile(userId = id)).",
        code = """
// Generated by KSP:
fun TraverseNavigator.navigateToProfile(userId: String, ...) =
    navigate(Profile(userId = userId), ...)

// Usage:
navigator.navigateToProfile(userId = "42")
        """.trimIndent(),
    ),
    SectionEntry(
        heading = "7. TraverseScreens — KSP output",
        body = "KSP generates a static TraverseScreens object with per-destination ScreenInfo vals baked in at compile time. No init call is needed — the JVM initialises it on first access.",
        code = """
// Zero-init — just access it:
val all: List<ScreenInfo> = TraverseScreens.all
val screens = TraverseScreens.screens
val deepLinkTargets = TraverseScreens.all
    .filter { it.deepLinkPatterns.isNotEmpty() }

// Per-destination accessor:
val info: ScreenInfo = TraverseScreens.catalog
        """.trimIndent(),
    ),
)

/**
 * Annotations showcase — explains the `@TraverseScreen`, `@DeepLink`, `@Transition`,
 * and `@ScreenMeta` annotations plus their KSP-generated outputs.
 *
 * @param onNavigateToItemDetail Navigate to a sample annotated destination using the
 *   KSP-generated `navigateToAnnotationItemDetail(itemId)` extension.
 * @param onBrowseRegistry Navigate to the live [ScreenRegistry] browser.
 * @param onNavigateUp Navigate back.
 */
@Composable
fun AnnotationsShowcaseScreen(
    onNavigateToItemDetail: (String) -> Unit,
    onBrowseRegistry: () -> Unit,
    onNavigateUp: () -> Unit,
) {
    ShowcaseScaffold(
        title = "Annotations + KSP",
        apiBadge = "@TraverseScreen",
        onBack = onNavigateUp,
    ) { innerPadding ->
        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(
                start = 16.dp,
                end = 16.dp,
                top = innerPadding.calculateTopPadding() + 8.dp,
                bottom = innerPadding.calculateBottomPadding() + 16.dp,
            ),
            verticalArrangement = Arrangement.spacedBy(12.dp),
        ) {
            // ── Intro ──────────────────────────────────────────────────────────
            item {
                InfoBanner(
                    text = "Annotate your Destination classes with @TraverseScreen, @DeepLink, " +
                        "@Transition, or @ScreenMeta. Add ksp(traverse-ksp-processor) to your " +
                        "build and the processor generates type-safe helpers automatically.",
                )
            }

            // ── Live registry summary + Browse button ──────────────────────────
            item {
                ScreenRegistrySummaryCard(onBrowseRegistry = onBrowseRegistry)
            }

            // ── "Try it" live example ──────────────────────────────────────────
            item {
                TryItCard(onNavigateToItemDetail = onNavigateToItemDetail)
            }

            // ── Section cards ──────────────────────────────────────────────────
            items(OVERVIEW_SECTIONS, key = { it.heading }) { section ->
                SectionCard(section)
            }
        }
    }
}

@Composable
private fun InfoBanner(text: String) {
    Surface(
        color = MaterialTheme.colorScheme.secondaryContainer,
        contentColor = MaterialTheme.colorScheme.onSecondaryContainer,
        shape = MaterialTheme.shapes.medium,
        modifier = Modifier.fillMaxWidth(),
    ) {
        Text(
            text = text,
            modifier = Modifier.padding(16.dp),
            style = MaterialTheme.typography.bodyMedium,
        )
    }
}

@Composable
private fun ScreenRegistrySummaryCard(onBrowseRegistry: () -> Unit) {
    val allEntries = TraverseScreens.all
    val screenCount = TraverseScreens.screens.size
    val dialogCount = TraverseScreens.dialogs.size
    val sheetCount = TraverseScreens.bottomSheets.size
    val deepLinkCount = allEntries.count { it.deepLinkPatterns.isNotEmpty() }

    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer),
    ) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text(
                "TraverseScreens — compile-time catalogue",
                style = MaterialTheme.typography.titleSmall,
                color = MaterialTheme.colorScheme.onPrimaryContainer,
            )
            Text(
                text = "${allEntries.size} destinations — baked in at KSP time, zero init required:\n" +
                    "  🖥 $screenCount screens · 💬 $dialogCount dialogs · 📋 $sheetCount sheets · 🔗 $deepLinkCount with deep links",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onPrimaryContainer,
            )
            Text(
                text = "Groups: " + allEntries.mapNotNull { it.group.takeIf { g -> g.isNotBlank() } }
                    .distinct().sorted().joinToString(", "),
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onPrimaryContainer,
            )
            Spacer(Modifier.height(4.dp))
            Button(
                onClick = onBrowseRegistry,
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text("Browse TraverseScreens →  (${allEntries.size} destinations)")
            }
        }
    }
}

@Composable
private fun TryItCard(onNavigateToItemDetail: (String) -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.tertiaryContainer),
    ) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text(
                "Try it — type-safe navigation",
                style = MaterialTheme.typography.titleSmall,
                color = MaterialTheme.colorScheme.onTertiaryContainer,
            )
            Text(
                text = "AnnotationItemDetail is annotated with @TraverseScreen, @DeepLink, and @Transition. " +
                    "The KSP processor generated navigateToAnnotationItemDetail(itemId) for it.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onTertiaryContainer,
            )
            Text(
                text = "// KSP-generated call:\nnavigator.navigateToAnnotationItemDetail(itemId = \"demo-42\")",
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onTertiaryContainer,
                fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
            )
            FilledTonalButton(
                onClick = { onNavigateToItemDetail("demo-42") },
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text("→ Navigate to AnnotationItemDetail")
            }
        }
    }
}

@Composable
private fun SectionCard(section: SectionEntry) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceContainerLow),
    ) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text(text = section.heading, style = MaterialTheme.typography.titleSmall)
            Text(
                text = section.body,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            if (section.code != null) {
                Spacer(Modifier.height(4.dp))
                Surface(
                    color = MaterialTheme.colorScheme.surfaceContainerHighest,
                    shape = MaterialTheme.shapes.small,
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Text(
                        text = section.code,
                        modifier = Modifier.padding(12.dp),
                        style = MaterialTheme.typography.labelSmall,
                        fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                        color = MaterialTheme.colorScheme.onSurface,
                    )
                }
            }
        }
    }
}

// ── AnnotationItemDetailScreen ────────────────────────────────────────────────

/**
 * Sample detail screen for the annotations demo.
 * This destination is annotated with `@TraverseScreen`, `@DeepLink`, and `@Transition`
 * so the KSP processor generates `navigateToAnnotationItemDetail(itemId)` for it.
 */
@Composable
fun AnnotationItemDetailScreen(
    itemId: String,
    onNavigateUp: () -> Unit,
) {
    ShowcaseScaffold(
        title = "Item Detail",
        apiBadge = "@DeepLink",
        onBack = onNavigateUp,
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(24.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp),
        ) {
            Text("Item ID: $itemId", style = MaterialTheme.typography.headlineSmall)
            Text(
                "This screen was reached via KSP-generated navigator.navigateToAnnotationItemDetail(itemId = \"$itemId\").",
                style = MaterialTheme.typography.bodyMedium,
            )
            Spacer(Modifier.height(8.dp))
            Text(
                "Its deep link pattern traverse://demo/annotations/item/{itemId} was also registered " +
                    "automatically by the KSP processor.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            Text(
                "Try deep-linking:\ntraverse://demo/annotations/item/my-item-123",
                style = MaterialTheme.typography.labelSmall,
                fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                color = MaterialTheme.colorScheme.primary,
            )
        }
    }
}






