package dev.teogor.traverse.demo

import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() = application {
    // Populate ScreenRegistry with all @TraverseScreen / @TraverseDialog / @TraverseBottomSheet
    // metadata generated by traverse-ksp-processor. Call once at startup — idempotent.
    initTraverseScreenRegistry()
    Window(
        onCloseRequest = ::exitApplication,
        title = "Traverse",
    ) {
        App()
    }
}

