package dev.teogor.traverse.annotations

import kotlin.reflect.KClass

/**
 * Runtime metadata record for a single annotated navigation destination.
 *
 * Instances are generated by `traverse-ksp-processor` and automatically registered in
 * [ScreenRegistry] via a generated initializer. On JVM/Android, the registry can also
 * be populated manually via [ScreenRegistry.register].
 *
 * @property klass The Kotlin class that implements [Destination][dev.teogor.traverse.core.Destination].
 * @property name Human-readable display name. Sourced from [ScreenMeta.name]; falls back to
 *   [klass]`.simpleName` when blank.
 * @property description Longer description of this destination's purpose.
 * @property group Logical grouping key (e.g. `"onboarding"`, `"account"`).
 * @property destinationType Whether this is a [DestinationType.SCREEN], [DestinationType.DIALOG],
 *   or [DestinationType.BOTTOM_SHEET].
 * @property isRoot `true` if the destination carries [@TraverseRoot][TraverseRoot].
 * @property deepLinkPatterns All URI patterns registered via [@DeepLink][DeepLink].
 *
 * @see ScreenRegistry
 * @see ScreenMeta
 */
public data class ScreenInfo(
    val klass: KClass<*>,
    val name: String,
    val description: String,
    val group: String,
    val destinationType: DestinationType,
    val isRoot: Boolean,
    val deepLinkPatterns: List<String>,
) {

    /**
     * The type of a navigation destination as declared via `@TraverseScreen`, `@TraverseDialog`,
     * or `@TraverseBottomSheet`.
     */
    public enum class DestinationType {
        /** Full-screen composable — registered via `screen<T>`. */
        SCREEN,

        /** Compose Dialog overlay — registered via `dialog<T>`. */
        DIALOG,

        /** ModalBottomSheet overlay — registered via `bottomSheet<T>`. */
        BOTTOM_SHEET,
    }
}

/**
 * In-memory registry of all annotated navigation destinations.
 *
 * Populated automatically by the generated initializer when `traverse-ksp-processor` is used.
 * Can also be populated manually via [register] for destinations that are not processed by KSP.
 *
 * ## Generated usage (automatic)
 * ```kotlin
 * // traverseKspInit() is called from the generated initializer
 * ScreenRegistry.register(ScreenInfo(Home::class, name = "Home", ...))
 * ```
 *
 * ## Manual usage
 * ```kotlin
 * ScreenRegistry.register(ScreenInfo(MyScreen::class, name = "My Screen", ...))
 * val allScreens: List<ScreenInfo> = ScreenRegistry.all
 * val mainScreens = ScreenRegistry.byGroup("main")
 * ```
 *
 * @see ScreenInfo
 */
public object ScreenRegistry {

    private val _entries: MutableList<ScreenInfo> = mutableListOf()

    /** All registered destination infos in registration order. */
    public val all: List<ScreenInfo> get() = _entries.toList()

    /** Registers a [ScreenInfo] entry. Idempotent — duplicate [ScreenInfo.klass] entries are ignored. */
    public fun register(info: ScreenInfo) {
        if (_entries.none { it.klass == info.klass }) {
            _entries += info
        }
    }

    /** Returns all registered entries whose [ScreenInfo.group] equals [group]. */
    public fun byGroup(group: String): List<ScreenInfo> = _entries.filter { it.group == group }

    /** Returns all entries of [ScreenInfo.DestinationType.SCREEN]. */
    public val screens: List<ScreenInfo>
        get() = _entries.filter { it.destinationType == ScreenInfo.DestinationType.SCREEN }

    /** Returns all entries of [ScreenInfo.DestinationType.DIALOG]. */
    public val dialogs: List<ScreenInfo>
        get() = _entries.filter { it.destinationType == ScreenInfo.DestinationType.DIALOG }

    /** Returns all entries of [ScreenInfo.DestinationType.BOTTOM_SHEET]. */
    public val bottomSheets: List<ScreenInfo>
        get() = _entries.filter { it.destinationType == ScreenInfo.DestinationType.BOTTOM_SHEET }

    /** Clears all registered entries. Useful in tests between test cases. */
    public fun clear() {
        _entries.clear()
    }

    /** Returns the [ScreenInfo] for the given [klass], or `null` if not registered. */
    public fun get(klass: KClass<*>): ScreenInfo? = _entries.firstOrNull { it.klass == klass }
}

