tpackage dev.teogor.traverse.demo

import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.window.ComposeViewport

@OptIn(ExperimentalComposeUiApi::class)
fun main() {
    // Populate ScreenRegistry with all @TraverseScreen / @TraverseDialog / @TraverseBottomSheet
    // metadata generated by traverse-ksp-processor. Call once at startup — idempotent.
    initTraverseScreenRegistry()
    ComposeViewport {
        App()
    }
}

