package dev.teogor.traverse.ksp.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import dev.teogor.traverse.ksp.model.DestinationModel
import dev.teogor.traverse.ksp.model.DestinationType

private val HEADER = """
// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  Generated by traverse-ksp-processor — DO NOT EDIT                          ║
// ║  Source: https://github.com/teogor/traverse                                 ║
// ╚══════════════════════════════════════════════════════════════════════════════╝
""".trimIndent()

/** Maps a [TransitionPreset][dev.teogor.traverse.annotations.TransitionPreset] enum name to its factory call. */
private fun transitionPresetToCall(preset: String, duration: Int): String = when (preset) {
    "HORIZONTAL_SLIDE" -> "TraverseTransitionSpec.horizontalSlide($duration)"
    "VERTICAL_SLIDE"   -> "TraverseTransitionSpec.verticalSlide($duration)"
    "SLIDE_AND_FADE"   -> "TraverseTransitionSpec.slideAndFade($duration)"
    "SCALE_AND_FADE"   -> "TraverseTransitionSpec.scaleAndFade($duration)"
    "ELEVATE"          -> "TraverseTransitionSpec.elevate($duration)"
    "NONE"             -> "TraverseTransitionSpec.none()"
    else               -> "TraverseTransitionSpec.fade($duration)"  // default: FADE
}

/**
 * Generates `TraverseAutoGraph.kt` — a single aggregating function that calls the correct
 * `screen<T>`, `dialog<T>`, or `bottomSheet<T>` registration for every annotated destination
 * found across all processed source files.
 *
 * Generated file location: the package of the first processed destination (or `traverseAutoGraph`
 * if models have mixed packages — the function is placed in the shortest common package).
 *
 * ## Example output
 *
 * ```kotlin
 * public fun TraverseGraphBuilder.traverseAutoGraph(
 *     homeContent: @Composable (Home) -> Unit,
 *     profileContent: @Composable (Profile) -> Unit,
 *     confirmDeleteContent: @Composable (ConfirmDelete) -> Unit,
 * ) {
 *     screen<Home>(content = homeContent)
 *     screen<Profile>(
 *         transitionSpec = TraverseTransitionSpec.horizontalSlide(300),
 *         deepLinks = ProfileRoute.deepLinks,
 *         content = profileContent,
 *     )
 *     dialog<ConfirmDelete>(content = confirmDeleteContent)
 * }
 * ```
 *
 * Also generates a `TraverseScreenRegistry.kt` file containing a `@Composable` `RegisterTraverseScreens()`
 * function that populates [ScreenRegistry][dev.teogor.traverse.annotations.ScreenRegistry] once per
 * composition tree via [androidx.compose.runtime.remember].
 */
public class GraphSpecGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) {
    public fun generate(models: List<DestinationModel>) {
        if (models.isEmpty()) return

        val targetPackage = commonPackage(models.map { it.packageName })
        generateAutoGraph(models, targetPackage)
        generateTraverseScreensObject(models, targetPackage)
    }

    // ── traverseAutoGraph() ────────────────────────────────────────────────────

    private fun generateAutoGraph(models: List<DestinationModel>, targetPackage: String) {
        val fileName = "TraverseAutoGraph"
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true),
            packageName = targetPackage,
            fileName = fileName,
        )

        val sb = StringBuilder()
        sb.appendLine(HEADER)
        sb.appendLine()
        if (targetPackage.isNotEmpty()) {
            sb.appendLine("package $targetPackage")
            sb.appendLine()
        }
        sb.appendLine("import androidx.compose.runtime.Composable")
        sb.appendLine("import dev.teogor.traverse.compose.graph.TraverseGraphBuilder")

        // Collect all imports needed
        val needsTransitionSpec = models.any { it.transitionInfo != null }
        if (needsTransitionSpec) {
            sb.appendLine("import dev.teogor.traverse.compose.transition.TraverseTransitionSpec")
        }
        val needsDeepLinks = models.any { it.deepLinkPatterns.isNotEmpty() }

        // Import destination classes (only if in different packages)
        models.map { it.packageName }.distinct().forEach { pkg ->
            if (pkg != targetPackage && pkg.isNotEmpty()) {
                // Import all destinations from that package
                val destClassNames = models.filter { it.packageName == pkg }.map { it.className }
                destClassNames.forEach { name ->
                    sb.appendLine("import $pkg.$name")
                }
                if (needsDeepLinks) {
                    models.filter { it.packageName == pkg && it.deepLinkPatterns.isNotEmpty() }
                        .forEach { model ->
                            sb.appendLine("import $pkg.${model.className}Route")
                        }
                }
            }
        }

        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Registers all Traverse-annotated destinations in this module.")
        sb.appendLine(" *")
        sb.appendLine(" * Call this function inside a [TraverseHost][dev.teogor.traverse.compose.TraverseHost] `{ }` block:")
        sb.appendLine(" * ```kotlin")
        sb.appendLine(" * TraverseHost(startDestination = Home) {")
        sb.appendLine(" *     traverseAutoGraph(")
        models.take(3).forEach { m ->
            val argName = m.className.replaceFirstChar { it.lowercaseChar() } + "Content"
            sb.appendLine(" *         $argName = { ${m.className.replaceFirstChar { it.lowercaseChar() } }Screen() },")
        }
        if (models.size > 3) sb.appendLine(" *         ...")
        sb.appendLine(" *     )")
        sb.appendLine(" * }")
        sb.appendLine(" * ```")
        sb.appendLine(" *")
        sb.appendLine(" * Generated by `traverse-ksp-processor`.")
        sb.appendLine(" */")

        sb.appendLine("public fun TraverseGraphBuilder.traverseAutoGraph(")
        // Generate one content lambda parameter per destination
        models.forEach { model ->
            val argName = model.className.replaceFirstChar { it.lowercaseChar() } + "Content"
            val lambdaType = if (model.isObject) {
                "() -> Unit"
            } else {
                "(${model.className}) -> Unit"
            }
            sb.appendLine("    $argName: @Composable $lambdaType,")
        }
        sb.appendLine(") {")

        models.forEach { model ->
            val argName = model.className.replaceFirstChar { it.lowercaseChar() } + "Content"
            when (model.type) {
                DestinationType.SCREEN -> generateScreenRegistration(sb, model, argName)
                DestinationType.DIALOG -> generateDialogRegistration(sb, model, argName)
                DestinationType.BOTTOM_SHEET -> generateBottomSheetRegistration(sb, model, argName)
            }
        }

        sb.appendLine("}")
        sb.appendLine()

        file.write(sb.toString().toByteArray())
        file.close()
        logger.info("traverse-ksp: generated TraverseAutoGraph in $targetPackage (${models.size} destinations)")
    }

    private fun generateScreenRegistration(sb: StringBuilder, model: DestinationModel, argName: String) {
        val hasTransition = model.transitionInfo != null
        val hasDeepLinks = model.deepLinkPatterns.isNotEmpty()

        if (!hasTransition && !hasDeepLinks) {
            // Simple one-liner
            if (model.isObject) {
                sb.appendLine("    screen<${model.className}>(content = { $argName() })")
            } else {
                sb.appendLine("    screen<${model.className}>(content = $argName)")
            }
        } else {
            sb.appendLine("    screen<${model.className}>(")
            if (hasTransition && model.transitionInfo != null) {
                val spec = transitionPresetToCall(model.transitionInfo.preset, model.transitionInfo.durationMillis)
                sb.appendLine("        transitionSpec = $spec,")
            }
            if (hasDeepLinks) {
                sb.appendLine("        deepLinks = ${model.className}Route.deepLinks,")
            }
            if (model.isObject) {
                sb.appendLine("        content = { $argName() },")
            } else {
                sb.appendLine("        content = $argName,")
            }
            sb.appendLine("    )")
        }
    }

    private fun generateDialogRegistration(sb: StringBuilder, model: DestinationModel, argName: String) {
        if (model.isObject) {
            sb.appendLine("    dialog<${model.className}>(content = { $argName() })")
        } else {
            sb.appendLine("    dialog<${model.className}>(content = $argName)")
        }
    }

    private fun generateBottomSheetRegistration(sb: StringBuilder, model: DestinationModel, argName: String) {
        if (model.isObject) {
            sb.appendLine("    bottomSheet<${model.className}>(content = { $argName() })")
        } else {
            sb.appendLine("    bottomSheet<${model.className}>(content = $argName)")
        }
    }

    // ── TraverseScreens static object ─────────────────────────────────────────
    //
    // Inspired by Compose Destinations' NavGraphs pattern: a plain Kotlin object
    // whose properties are initialised by the JVM on first access — zero runtime
    // registration calls required anywhere in application code.

    private fun generateTraverseScreensObject(models: List<DestinationModel>, targetPackage: String) {
        val fileName = "TraverseScreens"
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true),
            packageName = targetPackage,
            fileName = fileName,
        )

        val sb = StringBuilder()
        sb.appendLine(HEADER)
        sb.appendLine()
        if (targetPackage.isNotEmpty()) {
            sb.appendLine("package $targetPackage")
            sb.appendLine()
        }
        sb.appendLine("import dev.teogor.traverse.annotations.ScreenInfo")
        sb.appendLine("import dev.teogor.traverse.annotations.ScreenInfo.DestinationType")
        sb.appendLine()

        // Import destination classes from other packages
        models.map { it.packageName }.distinct().forEach { pkg ->
            if (pkg != targetPackage && pkg.isNotEmpty()) {
                models.filter { it.packageName == pkg }.forEach { model ->
                    sb.appendLine("import ${model.qualifiedName}")
                }
            }
        }

        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Compile-time catalogue of every `@TraverseScreen`, `@TraverseDialog`, and")
        sb.appendLine(" * `@TraverseBottomSheet` destination in this module.")
        sb.appendLine(" *")
        sb.appendLine(" * Metadata is baked in at KSP time and initialised lazily by the JVM on first")
        sb.appendLine(" * access — **no explicit registration call is required**.")
        sb.appendLine(" *")
        sb.appendLine(" * ```kotlin")
        sb.appendLine(" * // Access the full list:")
        sb.appendLine(" * val all: List<ScreenInfo> = TraverseScreens.all")
        sb.appendLine(" *")
        sb.appendLine(" * // Access a single destination's metadata:")
        sb.appendLine(" * val info: ScreenInfo = TraverseScreens.catalog")
        sb.appendLine(" *")
        sb.appendLine(" * // Filter by group:")
        sb.appendLine(" * val onboarding = TraverseScreens.byGroup(\"onboarding\")")
        sb.appendLine(" * ```")
        sb.appendLine(" *")
        sb.appendLine(" * Generated by `traverse-ksp-processor`.")
        sb.appendLine(" */")
        sb.appendLine("public object TraverseScreens {")
        sb.appendLine()

        // Per-destination vals (camelCase lowercase first letter to avoid clash with the class name)
        models.forEach { model ->
            val propName = model.className.replaceFirstChar { it.lowercaseChar() }
            val type = when (model.type) {
                DestinationType.SCREEN      -> "DestinationType.SCREEN"
                DestinationType.DIALOG      -> "DestinationType.DIALOG"
                DestinationType.BOTTOM_SHEET -> "DestinationType.BOTTOM_SHEET"
            }
            val name        = model.meta?.name?.takeIf { it.isNotBlank() } ?: model.className
            val description = model.meta?.description ?: ""
            val group       = model.meta?.group ?: ""
            val deepLinks   = if (model.deepLinkPatterns.isEmpty()) "emptyList()"
                              else "listOf(${model.deepLinkPatterns.joinToString(", ") { "\"$it\"" }})"

            sb.appendLine("    /** [ScreenInfo] for [${model.className}]. */")
            sb.appendLine("    public val $propName: ScreenInfo = ScreenInfo(")
            sb.appendLine("        klass = ${model.className}::class,")
            sb.appendLine("        name = \"$name\",")
            sb.appendLine("        description = \"$description\",")
            sb.appendLine("        group = \"$group\",")
            sb.appendLine("        destinationType = $type,")
            sb.appendLine("        isRoot = ${model.isRoot},")
            sb.appendLine("        deepLinkPatterns = $deepLinks,")
            sb.appendLine("    )")
            sb.appendLine()
        }

        // Aggregate lists — declared after the per-destination vals so object init order is correct
        val propNames = models.map { it.className.replaceFirstChar { it.lowercaseChar() } }
        sb.appendLine("    /** All annotated destinations in this module, in declaration order. */")
        sb.appendLine("    public val all: List<ScreenInfo> = listOf(")
        propNames.forEach { sb.appendLine("        $it,") }
        sb.appendLine("    )")
        sb.appendLine()
        sb.appendLine("    /** Destinations of type [DestinationType.SCREEN]. */")
        sb.appendLine("    public val screens: List<ScreenInfo> = all.filter { it.destinationType == DestinationType.SCREEN }")
        sb.appendLine()
        sb.appendLine("    /** Destinations of type [DestinationType.DIALOG]. */")
        sb.appendLine("    public val dialogs: List<ScreenInfo> = all.filter { it.destinationType == DestinationType.DIALOG }")
        sb.appendLine()
        sb.appendLine("    /** Destinations of type [DestinationType.BOTTOM_SHEET]. */")
        sb.appendLine("    public val bottomSheets: List<ScreenInfo> = all.filter { it.destinationType == DestinationType.BOTTOM_SHEET }")
        sb.appendLine()
        sb.appendLine("    /** Returns all destinations whose [ScreenInfo.group] equals [group]. */")
        sb.appendLine("    public fun byGroup(group: String): List<ScreenInfo> = all.filter { it.group == group }")
        sb.appendLine("}")
        sb.appendLine()

        file.write(sb.toString().toByteArray())
        file.close()
        logger.info("traverse-ksp: generated TraverseScreens object in $targetPackage (${models.size} destinations)")
    }

    // ── Utilities ──────────────────────────────────────────────────────────────

    /**
     * Computes the longest common package prefix across all destination packages.
     * Falls back to the first model's package when packages are entirely disjoint.
     */
    private fun commonPackage(packages: List<String>): String {
        if (packages.isEmpty()) return ""
        if (packages.size == 1) return packages.first()

        val parts = packages.map { it.split(".") }
        val shortest = parts.minByOrNull { it.size } ?: return packages.first()
        val common = mutableListOf<String>()
        for (i in shortest.indices) {
            val segment = shortest[i]
            if (parts.all { it.getOrNull(i) == segment }) common += segment else break
        }
        return common.joinToString(".")
    }
}


