package dev.teogor.traverse.ksp.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import dev.teogor.traverse.ksp.model.DestinationModel
import dev.teogor.traverse.ksp.model.DestinationType

private val HEADER = """
// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  Generated by traverse-ksp-processor — DO NOT EDIT                          ║
// ║  Source: https://github.com/teogor/traverse                                 ║
// ╚══════════════════════════════════════════════════════════════════════════════╝
""".trimIndent()

/**
 * Generates `{ClassName}NavigatorExtensions.kt` containing a type-safe
 * `TraverseNavigator.navigateTo{ClassName}(params...)` extension function.
 *
 * Only generated for [DestinationType.SCREEN] destinations that have at least one non-default
 * constructor parameter. For `data object` destinations (no params) and for dialogs / bottom
 * sheets, the extension is omitted (callers can use `navigator.navigate(MyDestination)` directly).
 *
 * Example output for `data class Profile(val userId: String)`:
 * ```kotlin
 * public fun TraverseNavigator.navigateToProfile(
 *     userId: String,
 *     builder: NavOptions.() -> Unit = {},
 * ): Unit = navigate(Profile(userId = userId), builder)
 * ```
 */
public class NavigatorExtensionGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) {
    public fun generate(model: DestinationModel) {
        // Only generate navigate extensions for screens + dialogs with required parameters
        val requiredParams = model.parameters.filter { !it.hasDefault }
        if (requiredParams.isEmpty()) return  // data objects and all-default params → skip

        val fileName = "${model.className}NavigatorExtensions"
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false),
            packageName = model.packageName,
            fileName = fileName,
        )

        val sb = StringBuilder()
        sb.appendLine(HEADER)
        sb.appendLine()
        if (model.packageName.isNotEmpty()) {
            sb.appendLine("package ${model.packageName}")
            sb.appendLine()
        }
        sb.appendLine("import dev.teogor.traverse.core.navigator.NavOptions")
        sb.appendLine("import dev.teogor.traverse.core.navigator.TraverseNavigator")
        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Type-safe navigation to [${model.className}].")
        sb.appendLine(" *")
        if (model.meta?.description?.isNotBlank() == true) {
            sb.appendLine(" * ${model.meta.description}")
            sb.appendLine(" *")
        }
        sb.appendLine(" * Generated by `traverse-ksp-processor`.")
        sb.appendLine(" */")

        val paramDeclarations = requiredParams.joinToString(",\n    ") { p ->
            val nullable = if (p.isNullable) "?" else ""
            "${p.name}: ${p.typeName}$nullable"
        }
        val constructorArgs = requiredParams.joinToString(", ") { p -> "${p.name} = ${p.name}" }

        sb.appendLine("public fun TraverseNavigator.navigateTo${model.className}(")
        sb.appendLine("    $paramDeclarations,")
        sb.appendLine("    builder: NavOptions.() -> Unit = {},")
        sb.appendLine("): Unit = navigate(${model.className}($constructorArgs), builder)")
        sb.appendLine()

        file.write(sb.toString().toByteArray())
        file.close()
        logger.info("traverse-ksp: generated $fileName in ${model.packageName}")
    }
}

