package dev.teogor.traverse.ksp.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import dev.teogor.traverse.ksp.model.DestinationModel

private val HEADER = """
// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  Generated by traverse-ksp-processor — DO NOT EDIT                          ║
// ║  Source: https://github.com/teogor/traverse                                 ║
// ╚══════════════════════════════════════════════════════════════════════════════╝
""".trimIndent()

/**
 * Generates `{ClassName}Route.kt` containing:
 * - A `{ClassName}Route` object with all deep-link patterns as a `List<TraverseDeepLink>`.
 * - For data-class destinations (with parameters): a type-safe `buildDeepLink(params...)` helper
 *   that produces a concrete URI from the first registered pattern.
 *
 * Example output for `@TraverseScreen @DeepLink("https://example.com/user/{userId}") data class Profile(val userId: String)`:
 * ```kotlin
 * public object ProfileRoute {
 *     public val deepLinks: List<TraverseDeepLink> = listOf(
 *         deepLink("https://example.com/user/{userId}"),
 *     )
 *     public fun buildDeepLink(userId: String): String =
 *         "https://example.com/user/${userId}"
 * }
 * ```
 */
public class RouteObjectGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) {
    public fun generate(model: DestinationModel) {
        if (model.deepLinkPatterns.isEmpty()) return  // no deep links → no Route object needed

        val fileName = "${model.className}Route"
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false),
            packageName = model.packageName,
            fileName = fileName,
        )

        val sb = StringBuilder()
        sb.appendLine(HEADER)
        sb.appendLine()
        if (model.packageName.isNotEmpty()) {
            sb.appendLine("package ${model.packageName}")
            sb.appendLine()
        }
        sb.appendLine("import dev.teogor.traverse.compose.deeplink.TraverseDeepLink")
        sb.appendLine("import dev.teogor.traverse.compose.deeplink.deepLink")
        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Deep-link registration for [${model.className}].")
        sb.appendLine(" *")
        sb.appendLine(" * Generated by `traverse-ksp-processor`.")
        sb.appendLine(" */")
        sb.appendLine("public object $fileName {")
        sb.appendLine()
        sb.appendLine("    /** All URI patterns registered via `@DeepLink` on [${model.className}]. */")
        sb.appendLine("    public val deepLinks: List<TraverseDeepLink> = listOf(")
        for (pattern in model.deepLinkPatterns) {
            sb.appendLine("""        deepLink("$pattern"),""")
        }
        sb.appendLine("    )")

        // Type-safe deep link builder for data-class destinations
        if (!model.isObject && model.parameters.isNotEmpty() && model.deepLinkPatterns.isNotEmpty()) {
            val firstPattern = model.deepLinkPatterns.first()
            // Extract all {paramName} placeholders from the first pattern
            val placeholderRegex = Regex("""\{(\w+)}""")
            val placeholders = placeholderRegex.findAll(firstPattern).map { it.groupValues[1] }.toList()
            // Only generate the builder if all placeholders match parameter names
            val paramNames = model.parameters.map { it.name }
            if (placeholders.isNotEmpty() && placeholders.all { it in paramNames }) {
                val requiredParams = model.parameters.filter { it.name in placeholders && !it.hasDefault }
                val paramListStr = requiredParams.joinToString(", ") { p ->
                    val nullable = if (p.isNullable) "?" else ""
                    "${p.name}: ${p.typeName}$nullable"
                }
                // Replace {param} in the pattern with $param interpolation
                val uriTemplate = firstPattern.replace(placeholderRegex) { "\${${it.groupValues[1]}}" }
                sb.appendLine()
                sb.appendLine("    /**")
                sb.appendLine("     * Builds a concrete deep-link URI for [${model.className}].")
                sb.appendLine("     * Uses pattern: `$firstPattern`")
                sb.appendLine("     */")
                sb.appendLine("    public fun buildDeepLink($paramListStr): String =")
                sb.appendLine("""        "$uriTemplate"""")
            }
        }

        sb.appendLine("}")
        sb.appendLine()

        file.write(sb.toString().toByteArray())
        file.close()
        logger.info("traverse-ksp: generated $fileName in ${model.packageName}")
    }
}

